### ISSUE TITLE
Method for verifying page <title> text

### ISSUE THREAD

**Issue by jonlindemannsonos** [zdfs/sonos-webdriverio#1]
I was trying to make sure that a collection of pages were all NOT returning a 404 as their <title> text (404 is the title of our default error page). It was discovered that we currently do not have a way to do this (verifyText returns a NULL), so a method would be needed (e.g. verifyTitle) to pull the <title> text off of a page for use in automated testing scenarios.

**Comment by zdfs** [comment]
This has been added. You can use it like so:

``` javascript
"verify": [
  "method": "verifyPageTitle",
  "asserts": {
    "title": "Sonos Suit"
  }
]
```
